security.protocol=SSL
ssl.keystore.location=/Users/nbargovic/code/cfk-k3s-sample/generated/keystore.jks
ssl.keystore.password=password
ssl.truststore.location=/Users/nbargovic/code/cfk-k3s-sample/generated/truststore.jks
ssl.truststore.password=password