apiVersion: platform.confluent.io/v1beta1
kind: Zookeeper
metadata:
  name: zookeeper
  namespace: confluent
spec:
  replicas: 3
  image:
    application: confluentinc/cp-zookeeper:7.3.1-1-ubi8
    init: confluentinc/confluent-init-container:2.5.1
  dataVolumeCapacity: 10Gi
  logVolumeCapacity: 5Gi
  authentication:
    type: mtls
    principalMappingRules:
      - RULE:.*CN[\s]?=[\s]?([a-zA-Z0-9.]*)?.*/$1/
  tls:
    secretRef: tls-zookeeper
  configOverrides:
    jvm:
      - "-Dcom.sun.management.jmxremote=false"
  podTemplate:
    podSecurityContext: {}
  license:
    globalLicense: true
---
apiVersion: platform.confluent.io/v1beta1
kind: Kafka
metadata:
  name: kafka
  namespace: confluent
spec:
  replicas: 3
  image:
    application: confluentinc/cp-server:7.3.1
    init: confluentinc/confluent-init-container:2.5.1
  dataVolumeCapacity: 25Gi
  configOverrides:
    server:
      - "confluent.support.metrics.enable=false"
      - "enable.fips=true"
      - "ssl.enabled.protocols=TLSv1.2"
    jvm:
      - "-Dcom.redhat.fips=true"
  fips:
    enabled: true
  tls:
    secretRef: fips-tls
  listeners:
    internal:
      authentication:
        type: mtls
        principalMappingRules:
          - RULE:.*CN[\s]?=[\s]?([a-zA-Z0-9.]*)?.*/$1/
      tls:
        enabled: true
    external:
      authentication:
        type: mtls
        principalMappingRules:
          - RULE:.*CN[\s]?=[\s]?([a-zA-Z0-9.]*)?.*/$1/
      tls:
        enabled: true
      externalAccess:
        type: route
        route:
          domain: apps.nbargovic-fips.pks4.p1.openshiftapps.com
  dependencies:
    zookeeper:
      endpoint: zookeeper.confluent.svc.cluster.local:2181
  podTemplate:
    podSecurityContext: {}
  license:
    globalLicense: true
