---
apiVersion: platform.confluent.io/v1beta1
kind: ControlCenter
metadata:
  name: controlcenter-next-gen
  namespace: confluent-nick
spec:
  replicas: 1
  image:
    application: confluentinc/cp-enterprise-control-center-next-gen:2.2.0
    init: confluentinc/confluent-init-container:3.0.0
  dataVolumeCapacity: 10Gi
  tls:
    secretRef: tls-controlcenter
  externalAccess:
    type: loadBalancer
    loadBalancer:
      domain: ps.eks.nick
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
  dependencies:
    prometheusClient:
      url: https://controlcenter-next-gen.confluent-nick.svc.cluster.local:9090
      authentication:
        type: basic
        basic:
          secretRef: prometheus-client-creds
      tls:
        enabled: true
        secretRef: tls-prometheus-client
    alertManagerClient:
      url: https://controlcenter-next-gen.confluent-nick.svc.cluster.local:9093
      authentication:
        type: basic
        basic:
          secretRef: alertmanager-client-creds
      tls:
        enabled: true
        secretRef: tls-alertmanager-client
  services:
    prometheus:
      image: confluentinc/cp-enterprise-prometheus:2.2.0
      authentication:
        type: basic
        basic:
          secretRef: prometheus-credentials
      tls:
        secretRef: tls-prometheus
      pvc:
        dataVolumeCapacity: 10Gi
    alertmanager:
      image: confluentinc/cp-enterprise-alertmanager:2.2.0
      authentication:
        type: basic
        basic:
          secretRef: alertmanager-credentials
      tls:
        secretRef: tls-alertmanager