apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp2
  uid: 84c449fd-eb6f-4bdd-bbba-a91392a66725
  resourceVersion: '1030500'
  creationTimestamp: '2025-06-02T13:11:30Z'
  labels:
    k8slens-edit-resource-version: v1
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"storage.k8s.io/v1","kind":"StorageClass","metadata":{"annotations":{},"name":"gp2"},"parameters":{"fsType":"ext4","type":"gp2"},"provisioner":"kubernetes.io/aws-ebs","volumeBindingMode":"WaitForFirstConsumer"}
    storageclass.kubernetes.io/is-default-class: 'true'
  selfLink: /apis/storage.k8s.io/v1/storageclasses/gp2
provisioner: kubernetes.io/aws-ebs
parameters:
  fsType: ext4
  type: gp2
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
